name: Run Unit Test

on:
  pull_request:
  # The branches below must be a subset of the branches above
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Branch
    - uses: actions/checkout@v1

    # Run Unit Test
    - name: Run Unit Test
      run: go test -v /loan/internal/services/test
   