name: Unit Test

on:
  pull_request:
    branches: [ staging ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Branch
    - uses: actions/checkout@v1

    # Run Unit Test
    - name: Run Unit Test
      run: go test -v internal/core/services/test
   